// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjCfDU7-rHmNXh9HkPHCEq_jx2OMXHILY',
    appId: '1:416063473702:web:d0b5f17379fb86b6613ee7',
    messagingSenderId: '416063473702',
    projectId: 'life-sync-81944',
    authDomain: 'life-sync-81944.firebaseapp.com',
    storageBucket: 'life-sync-81944.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3tHSxRLQ139pOfeAZzNJ3HJXpGF7dh14',
    appId: '1:416063473702:android:e5406a92114f98d7613ee7',
    messagingSenderId: '416063473702',
    projectId: 'life-sync-81944',
    storageBucket: 'life-sync-81944.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2VJCkmTP9gcnd2DewdAxlfCHZd0vqo68',
    appId: '1:416063473702:ios:c56bc6e6e26dc6c0613ee7',
    messagingSenderId: '416063473702',
    projectId: 'life-sync-81944',
    storageBucket: 'life-sync-81944.appspot.com',
    iosBundleId: 'com.example.lifeSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2VJCkmTP9gcnd2DewdAxlfCHZd0vqo68',
    appId: '1:416063473702:ios:c56bc6e6e26dc6c0613ee7',
    messagingSenderId: '416063473702',
    projectId: 'life-sync-81944',
    storageBucket: 'life-sync-81944.appspot.com',
    iosBundleId: 'com.example.lifeSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjCfDU7-rHmNXh9HkPHCEq_jx2OMXHILY',
    appId: '1:416063473702:web:7be5215a3d3c082f613ee7',
    messagingSenderId: '416063473702',
    projectId: 'life-sync-81944',
    authDomain: 'life-sync-81944.firebaseapp.com',
    storageBucket: 'life-sync-81944.appspot.com',
  );
}
